name: CI

on:
  pull_request:
  push:
    branches: [master]

jobs:
  ci:
    name: ci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - run: pnpm install --frozen-lockfile

      - run: pnpm build

      - run: node ../../packages/cli/dist/bin.js gen all
        working-directory: examples/api

      - run: pnpm typecheck

      - run: pnpm test
